#!/bin/bash

# Modify hosts file to change IP addresses
sudo sed -i 's/^127.0.0.1[[:space:]]*localhost$/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/^8.8.8.8[[:space:]]*facebook.com$/8.8.8.8 facebook.com/' /etc/hosts
