#!/usr/bin/env bash
# Create an RSA key pair with a passphrase

# Key name
KEY_NAME="school"

# Number of bits
BITS=4096

# Passphrase
PASSPHRASE="betty"

# Generate the key pair
ssh-keygen -b $BITS -t rsa -f $KEY_NAME -N "$PASSPHRASE"

echo "RSA key pair created:"
echo "Private key: $KEY_NAME"
echo "Public key: ${KEY_NAME}.pub"